#!/usr/bin/env ruby
# sudo-server multi-call script
require_relative 'component/client'
require_relative 'component/daemon'

$verbose = ENV['CREW_SUDO_VERBOSE'].eql?('1')

# resolve command arguments
case PROGNAME
when 'crew-sudo'
  case ARGV[0]
  when 'daemon'
    runas_daemon(ARGV[1..-1])
  when 'client'
    runas_client(ARGV[1..-1])
  when 'stop-daemon'
    exit(0) unless File.exist?(PID_FILE_PATH)
    pid = File.read(PID_FILE_PATH).to_i

    begin
      Process.kill('TERM', pid)
      warn "crew-sudo: Daemon with PID #{pid} stopped"
    rescue Errno::ESRCH
    end
  when '-h', '--help'
    warn <<~EOT
      #{File.basename($0)} multi-purpose launcher

      Usage: #{PROGNAME} [mode]
             #{PROGNAME} -h|--help
             #{PROGNAME} -V|--version

      Available commands:
        daemon       Run as daemon mode, listen incoming requests at #{SOCKET_PATH}
        client       Run as client mode, pass all given command arguments to daemon
        stop-daemon  Stop currently running crew-sudo daemon

    EOT
  when '-V', '--version'
    warn "#{PROGNAME} version 1.0"
  else
    warn <<~EOT
      #{PROGNAME}: Unknown option.

      Run '#{PROGNAME} --help' for usage.
    EOT
  end
when 'sudo'
  runas_client(ARGV)
end